# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(183, 361)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 250, 121, 16))
        self.label_6.setObjectName("label_6")
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(10, 20, 113, 21))
        self.nameEdit.setObjectName("nameEdit")
        self.roastEdit = QtWidgets.QLineEdit(Dialog)
        self.roastEdit.setGeometry(QtCore.QRect(10, 70, 113, 21))
        self.roastEdit.setObjectName("roastEdit")
        self.groundOrWholeEdit = QtWidgets.QLineEdit(Dialog)
        self.groundOrWholeEdit.setGeometry(QtCore.QRect(10, 120, 113, 21))
        self.groundOrWholeEdit.setObjectName("groundOrWholeEdit")
        self.flavorDescriptionEdit = QtWidgets.QLineEdit(Dialog)
        self.flavorDescriptionEdit.setGeometry(QtCore.QRect(10, 170, 113, 21))
        self.flavorDescriptionEdit.setObjectName("flavorDescriptionEdit")
        self.priceEdit = QtWidgets.QLineEdit(Dialog)
        self.priceEdit.setGeometry(QtCore.QRect(10, 220, 113, 21))
        self.priceEdit.setObjectName("priceEdit")
        self.packagingVolumeEdit = QtWidgets.QLineEdit(Dialog)
        self.packagingVolumeEdit.setGeometry(QtCore.QRect(10, 270, 113, 21))
        self.packagingVolumeEdit.setObjectName("packagingVolumeEdit")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(30, 310, 113, 32))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_3.setText(_translate("Dialog", "Цена"))
        self.label_4.setText(_translate("Dialog", "Молотый/в зернах"))
        self.label_5.setText(_translate("Dialog", "Описание вкуса"))
        self.label_6.setText(_translate("Dialog", "Объем упаковки"))
        self.saveButton.setText(_translate("Dialog", "Сохранить"))
